services:
  - type: web
    name: dcoder
    runtime: node
    plan: free
    branch: master
    buildCommand: npm ci && npm ci --prefix client && npm run build --prefix client
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGODB_URI
        sync: false
